"""Load Terms-of-Service and privacy-policy documents from disk.

We support the three formats real-world legal teams actually share:
  * .txt  - plain text dumps from legal review tooling
  * .md   - markdown versions produced by the contract management system
  * .pdf  - the format most ToS are published in
  * .docx - the format most internal redlines live in

Anything we can't parse is skipped with a warning, never raised - the
pipeline is allowed to run with a partial corpus.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

from pypdf import PdfReader
from docx import Document as DocxDocument

from src.utils.logging_setup import get_logger

_LOGGER = get_logger(__name__)


@dataclass
class LoadedDocument:
    """A single document after parsing, ready to be chunked.

    `source_path` is the absolute on-disk path the document was loaded from.
    For documents generated by the mock generator it points at the synthesized
    file inside `data/mock/`.
    """

    document_id: str
    title: str
    raw_text: str
    source_path: Path
    metadata: dict[str, str] = field(default_factory=dict)


# -- Format-specific readers ----------------------------------------------------


def _read_txt(path: Path) -> str:
    # Try utf-8 first; if the file is latin-1 (rare for ToS but possible from
    # legacy legal tooling) fall back gracefully rather than crashing.
    try:
        return path.read_text(encoding="utf-8").strip()
    except UnicodeDecodeError:
        return path.read_text(encoding="latin-1", errors="replace").strip()


def _read_pdf(path: Path) -> str:
    reader = PdfReader(str(path))
    page_texts: list[str] = []
    for index, page in enumerate(reader.pages):
        try:
            text = page.extract_text() or ""
        except Exception as exc:  # noqa: BLE001 - pypdf raises heterogeneous errors
            _LOGGER.warning("Failed to extract page %d from %s: %s", index, path.name, exc)
            text = ""
        if text:
            page_texts.append(_repair_pdf_text(text))
    return "\n\n".join(page_texts).strip()


# A lot of legal PDFs are typeset in narrow columns. pypdf's word-level
# extraction then returns one word per line, with single-space characters
# occupying their own lines. We detect that layout and coalesce the
# short lines back into proper prose.
_SHORT_LINE_THRESHOLD = 30  # chars - if the median line is shorter, treat as broken
_BULLET_PATTERN = re.compile(r"^\s*[\u25cf\u2022\-\*]\s")  # filled circle, bullet, dash, asterisk


def _repair_pdf_text(text: str) -> str:
    """Repair pypdf output for PDFs that came out one-word-per-line.

    Heuristic: if the median non-blank line length is below the
    threshold, we assume the PDF is using a narrow column layout and
    pypdf split every word (and even single spaces) onto its own line.
    In that case we coalesce the page into a single line of prose, then
    re-introduce paragraph breaks at obvious markers: bullet points
    (filled circle, bullet, dash, asterisk at the start of a line) and
    fully-blank lines (length-0, not just whitespace).

    If the median line length is normal, we leave the text alone - the
    extraction was already fine.
    """
    lines = text.splitlines()
    non_blank = [line for line in lines if line.strip()]
    if len(non_blank) < 4:
        # Too few lines to judge. Leave as-is.
        return text
    median_length = sorted(len(line) for line in non_blank)[len(non_blank) // 2]
    if median_length >= _SHORT_LINE_THRESHOLD:
        return text

    # Broken layout detected. Walk the lines, building prose, and break
    # a new paragraph whenever we see a bullet marker or a TRULY empty
    # line (length 0). Whitespace-only lines are treated as soft breaks
    # - just a continuation of the current prose, because pypdf emits
    # those for inter-word spaces in narrow-column layouts.
    paragraphs: list[str] = []
    current: list[str] = []

    def flush() -> None:
        if current:
            paragraphs.append(" ".join(current))
            current.clear()

    for line in lines:
        if not line:
            # Truly empty line: hard paragraph break.
            flush()
            continue
        stripped = line.strip()
        if not stripped:
            # Whitespace-only line: just a soft break, keep building.
            continue
        if _BULLET_PATTERN.match(stripped):
            # Bullet: start a new paragraph.
            flush()
            current.append(stripped)
            continue
        current.append(stripped)
    flush()

    # Collapse internal multi-spaces inside each paragraph.
    return "\n\n".join(re.sub(r"\s+", " ", p) for p in paragraphs)


def _read_docx(path: Path) -> str:
    document = DocxDocument(str(path))
    paragraphs = [paragraph.text for paragraph in document.paragraphs if paragraph.text]
    return "\n".join(paragraphs).strip()


_READERS = {
    ".txt": _read_txt,
    ".md": _read_txt,
    ".pdf": _read_pdf,
    ".docx": _read_docx,
}


def _load_one(path: Path) -> LoadedDocument | None:
    """Load a single file. Returns None if extraction yields empty text."""
    suffix = path.suffix.lower()
    reader = _READERS.get(suffix)
    if reader is None:
        _LOGGER.debug("Skipping unsupported file: %s", path)
        return None

    try:
        text = reader(path)
    except Exception as exc:  # noqa: BLE001
        _LOGGER.warning("Could not parse %s: %s", path.name, exc)
        return None

    if not text or len(text.strip()) < 20:
        # We refuse to ingest near-empty documents. They pollute the index
        # with garbage and produce false positives in retrieval.
        _LOGGER.warning("Discarding near-empty document: %s", path.name)
        return None

    title = path.stem.replace("_", " ").replace("-", " ").strip().title() or "Untitled"
    return LoadedDocument(
        document_id=path.stem,
        title=title,
        raw_text=text,
        source_path=path,
        metadata={"format": suffix.lstrip("."), "size_chars": str(len(text))},
    )


def discover_documents(
    directory: Path,
    supported_extensions: Iterable[str],
) -> list[LoadedDocument]:
    """Walk `directory` and return every parseable document we find."""
    directory = Path(directory)
    if not directory.exists():
        _LOGGER.warning("Documents directory does not exist: %s", directory)
        return []

    loaded: list[LoadedDocument] = []
    for path in sorted(directory.iterdir()):
        if not path.is_file():
            continue
        if path.suffix.lower() not in supported_extensions:
            continue
        document = _load_one(path)
        if document is not None:
            loaded.append(document)

    _LOGGER.info("Loaded %d document(s) from %s", len(loaded), directory)
    return loaded
